# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:faceauth
spring.jpa.hibernate.ddl-auto=update
python.url = https://your-render-python-url/api/process_face



spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
